### ISSUE TITLE
Unable to run 'npm run build' with rollup with latest dependencies

### ISSUE THREAD

**Issue by tonprince** [hperrin/smui-example-rollup#11]
I tried to run the rollup sample smui example but got the following error:

[!] (plugin postcss) Error: argument `$color` of `rgba($color, $alpha)` must be a color
node_modules/@smui/button/_index.scss
Error: argument `$color` of `rgba($color, $alpha)` must be a color
    at options.error (/Users/tonprincepro/Dropbox/Tripstore/Website/workspace/smui.test/node_modules/node-sass/lib/index.js:290:33)

**Comment by tonprince** [comment]
"devDependencies": {
    "@material/typography": "^9.0.0",
    "@smui/button": "^1.1.0",
    "rollup": "^2.35.1",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-postcss": "^4.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "postcss": "^8.2",
    "node-sass": "^5.0.0",
    "serve": "^11.3.2",
    "svelte": "^3.31.1"
  }

**Comment by 0cv** [comment]
similar issue, except than it's on `tab`
![image](https://user-images.githubusercontent.com/1253866/104817953-ee005c00-5824-11eb-91b1-14c34cefcb5b.png)
