### ISSUE TITLE
Does not build - sass is not configured properly

### ISSUE THREAD

**Issue by simonh1000** [hperrin/smui-example-rollup#4]
I came to this  repo to see how to configure sass, but there seems to be a problem with precisely sass

```
npm run build

> smui-example-rollup@1.0.0 build /Users/simonhampton/code/running/smui
> rollup -c rollup.config.js


index.js → dist/bundle.js...
[!] (plugin postcss) Error: You need to install either node-sass or sass in order to process Sass files
App.scss
Error: You need to install either node-sass or sass in order to process Sass files
```

**Comment by ollyg** [comment]
Indeed, it says your app will need a sass processor in the components repo read me:
https://github.com/hperrin/svelte-material-ui/blob/master/README.md

**Comment by simonh1000** [comment]
Yes, but several of us don't know how to work with that suggestion and were hoping to find a working example here

**Comment by ollyg** [comment]
Sorry, can't help you there. Would like to see the expanded example myself. I used the "bare" files option when testing: https://codesandbox.io/s/svelte-material-ui-example-gi8p3

**Comment by simonh1000** [comment]
the example for webpack does include what it takes to get it working so I've switched to that
